### ISSUE TITLE
[Bug] Duplication

### ISSUE THREAD

**Issue by jajohnston206** [PneumonoIsNotAvailable/Gravestones#55]
**Describe the bug**
When right clicking the gravestone it is not destroyed and instead can be used multiple times to get duplicates of your items

**Expected behavior**
Before this bug started right clicking the gravestone would destroy it and give you your items back 

**Version Information**
Minecraft Version: 1.21.1
Mod Version:
Mod List:
Cobblemon
Sophisticated Backpacks
Accessories/Trinkets
Tool Trims

**Comment by PneumonoIsNotAvailable** [comment]
Are you still experiencing this issue?

**Comment by genericblankslate** [comment]
After contacting the players, it was consistently happening after dying multiple times while trying to get their stuff from the gravestone.

**Comment by Vaz15k** [comment]
I get the same duplication issue. However, my case is with the Aether mod, and I also use Things and ElytraExtraSlot.

When I place any Aether gear in its proper slots, the tombstone gets infinitely glitched and duplicates my items. I believe it happens with Things too, but I'm not sure yet...

Note: Without the "Accessories with the Trinkets Compat Layer" mod, the bug does not occur.
And for logs, this is what I get in my server terminal:

> [07:57:53] [Server thread/INFO]: [Vaz15K: Killed Vaz15K]
> [07:57:56] [Server thread/INFO]: Vaz15K has found their grave at (1198, 72, -1683)
> [07:57:56] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@66087703, suppressing error
> java.lang.NullPointerException: Cannot invoke "dev.emi.trinkets.api.TrinketInventory.method_5438(int)" because "inventory" is null
> 	at net.pneumono.gravestones.compat.TrinketsDataType.lambda$onCollect$3(TrinketsDataType.java:104) ~[gravestones-1.1.8+1.20.1.jar:?]
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
> 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
> 	at net.pneumono.gravestones.compat.TrinketsDataType.onCollect(TrinketsDataType.java:111) ~[gravestones-1.1.8+1.20.1.jar:?]
> 	at net.pneumono.gravestones.api.GravestonesApi.onCollect(GravestonesApi.java:104) ~[gravestones-1.1.8+1.20.1.jar:?]
> 	at net.pneumono.gravestones.block.TechnicalGravestoneBlock.method_9534(TechnicalGravestoneBlock.java:85) ~[gravestones-1.1.8+1.20.1.jar:?]
> 	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_3225.method_14262(class_3225.java:343) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_3244.method_12046(class_3244.java:1140) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:15318) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.mixinextras$bridge$method_18857$297(MinecraftServer.java) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.wrapOperation$ebi000$modernfix$managedBlock(MinecraftServer.java:1823) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
> 	at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by PneumonoIsNotAvailable** [comment]
As far as I can tell, this seems to be an issue with the Trinkets Compat Layer not perfectly mirroring regular Trinkets. Currently Gravestones tries to use the compat layers instead of Accessories itself whenever it detects them, but in hindsight I think it's better to interact with Accessories directly to avoid issues like this, so I've changed it to do that which should fix this issue. I'll leave the issue open until I release the update.

**Comment by Bagellite** [comment]
Hey there, just wanted to add that even after replacing Trinkets compat layer with Accessories Compat Layer, the same bug as the one described in [#57 ](url) still occurs on my end.

Appreciate the work you do!! :)
